Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2020-10, with the labels that each got.

#19 Improve controller settings
  charts/gardener-extension-shoot-dns-service/templates/deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/vpa.yaml
  charts/gardener-extension-shoot-dns-service/values.yaml
  cmd/gardener-extension-shoot-dns-service/app/app.go
  cmd/gardener-extension-shoot-dns-service/app/options.go
  example/controller-registration.yaml
  pkg/cmd/options.go
  pkg/controller/common/env.go
  pkg/controller/config/config.go
  pkg/controller/healthcheck/add.go
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/add.go
  pkg/controller/replication/add.go
  pkg/controller/replication/reconciler.go
Labels: area/quality, area/usability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm

#22 fixing panic on deleting multiple DNS entries from state
  pkg/controller/common/state.go
  pkg/controller/common/state_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: area/control-plane, kind/bug, needs/ok-to-test, priority/normal, reviewed/lgtm, size/s

#23 add priority class for extension pods
  charts/gardener-extension-shoot-dns-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-dns-service/templates/deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/priorityclass.yaml
  example/controller-registration.yaml
Labels: area/high-availability, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs
