Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2021-06, with the labels that each got.

#56 avoid conflicting updates of the `status.state` of the extension resource by the replication controller
  pkg/controller/common/env.go
  pkg/controller/common/state.go
  pkg/controller/common/utils.go
  pkg/controller/lifecycle/actuator.go
  pkg/controller/replication/reconciler.go
  pkg/controller/replication/replication_suite_test.go
  pkg/controller/replication/stringslock.go
  pkg/controller/replication/stringslock_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/lgtm, size/m

#62 fix component descriptor script
  .ci/component_descriptor
Labels: needs/ok-to-test, needs/review, size/xs

#67 Add permissions for leader election lease of shoot-dns-service in control plane
  charts/internal/shoot-dns-service-shoot/templates/rbac.yaml
Labels: area/control-plane, kind/technical-debt, needs/ok-to-test, needs/review, size/s

#68 Add a link to the cherry-pick-pr script from gardener
  Makefile
  hack/cherry-pick-pull.sh
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
