Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2022-08, with the labels that each got.

#145 Add optional deployment for dns-controller-manager
  charts/gardener-extension-shoot-dns-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-dns-service/templates/configmap-imagevector-overwrite.yaml
  charts/gardener-extension-shoot-dns-service/templates/deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrole.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrolebinding.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-crds.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-hostedzonepolicies.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-psp.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-role.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-rolebinding.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-secret-remoteaccess.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-service-remoteaccess.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-serviceaccount.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-vpa.yaml
  charts/gardener-extension-shoot-dns-service/templates/rbac-shoot-dns-controller.yaml
  charts/gardener-extension-shoot-dns-service/templates/rbac.yaml
  charts/gardener-extension-shoot-dns-service/templates/secret-remote-default-domain.yaml
  charts/gardener-extension-shoot-dns-service/templates/serviceaccount.yaml
  charts/gardener-extension-shoot-dns-service/templates/vpa.yaml
  charts/gardener-extension-shoot-dns-service/values.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#148 Remove install-requirement and use tools.mk
  Makefile
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#147 Update to golang-1.18.5
  Dockerfile
Labels: needs/ok-to-test, needs/review, size/xs

#150 Fix name of podsecuritypolicy in cluster role for dns-controller-manager.
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrole.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#152 Fix the Shoot DNS integration test
  test/system/shootdns_test.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#151 Added section for deploying DNS controller manager
  docs/installation/setup.md
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#153 Don't deploy `PSP`s for cluster versions `>=1.24`
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrole.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-psp.yaml
  example/controller-registration.yaml
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#157 Fix indentation for controllerdeployment
  docs/installation/setup.md
Labels: area/documentation, kind/bug, needs/ok-to-test, reviewed/lgtm, size/s

#155 Improve message on stucking dnsentry deletion
  pkg/controller/lifecycle/actuator.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s
