Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2022-09, with the labels that each got.

#158 Fix failing test for ARM shoot
  test/resources/templates/echoserver-app.yaml.tpl
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#161 Handle `PodDisruptionBudget` `policy/v1`
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/poddisruptionbudget.yaml
  charts/internal/shoot-dns-service-seed/charts/utils-templates/templates/0versions.tpl
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#162 Fixed broken links - 2022.09
  docs/installation/setup.md
  docs/usage/dns_names.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
