Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2022-07, with the labels that each got.

#141 No predefined resources
  charts/gardener-extension-shoot-dns-service/values.yaml
  example/controller-registration.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#135 Add docu for DNSAnnotation resources
  docs/usage/dns_names.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/s

#144 Docs/more dns info
  CONTRIBUTING.md
  docs/usage/dns_names.md
Labels: area/documentation, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m
