Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2022-05, with the labels that each got.

#123 Minor docu improvement
  docs/usage/dns_names.md
Labels: needs/ok-to-test, needs/review, size/s

#125 Fix integration test TestDefinition
  .test-defs/shootdns-test.yaml
  test/system/shootdns_test.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#127 Improved liveness probe for admission webhook
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/values.yaml
  cmd/gardener-extension-admission-shoot-dns-service/app/app.go
  vendor/github.com/gardener/gardener/pkg/healthz/default.go
  vendor/github.com/gardener/gardener/pkg/healthz/healthz.go
  vendor/github.com/gardener/gardener/pkg/healthz/informer.go
  vendor/github.com/gardener/gardener/pkg/healthz/periodic.go
  vendor/modules.txt
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/s

#130 Update limits limit. Disable limit autoscaling.
  charts/internal/shoot-dns-service-seed/templates/vpa.yaml
  charts/internal/shoot-dns-service-seed/values.yaml
Labels: area/robustness, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling
