Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2023-12, with the labels that each got.

#269 Always create ServiceAccount in Runtime Cluster
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/serviceaccount.yaml
  example/50-mutatingwebhookconfiguration.yaml
  example/50-validatingwebhookconfiguration.yaml
  example/admission-shoot-dns-service-certs/tls.crt
  example/admission-shoot-dns-service-certs/tls.key
Labels: area/open-source, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#271 switch GCR -> Artifact-Registry
  .ci/component_descriptor
  .ci/pipeline_definitions
  Makefile
  charts/gardener-extension-admission-shoot-dns-service/charts/application/values.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/values.yaml
  charts/gardener-extension-admission-shoot-dns-service/values.yaml
  charts/gardener-extension-shoot-dns-service/values-test.yaml
  charts/gardener-extension-shoot-dns-service/values.yaml
  charts/images.yaml
  docs/operations/deployment.md
  example/12-resource-manager-shoot.yaml
  example/13-resource-manager-seed.yaml
  example/controller-registration.yaml
  example/extension.yaml
  imagevector/images.yaml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#273 Update dependabot workflow after removing vendoring
  .github/workflows/vendor_gardener.yaml
Labels: area/dev-productivity, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#275 fix: remove erroneous overwrite
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
