Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2023-05, with the labels that each got.

#207 Bump golang image to 1.20.3
  .test-defs/shootdns-test.yaml
  Dockerfile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#210 Adapt `NetworkPolicy`s
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-service.yaml
  charts/gardener-extension-shoot-dns-service/templates/service.yaml
  example/controller-registration.yaml
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#211 topology-aware routing: Adapt to the upstream annotation change in K8s 1.27
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/service.yaml
Labels: area/high-availability, area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs
