Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2023-01, with the labels that each got.

#177 Drop support for kubernetes < 1.20 for shoot dns extension
  charts/internal/shoot-dns-service-seed/charts/utils-templates/templates/0versions.tpl
  example/10-fake-shoot-controlplane.yaml
  example/30-cluster.yaml
  go.mod
  hack/api-reference/api.json
  hack/api-reference/config.json
  hack/api-reference/service.json
  pkg/controller/lifecycle/actuator.go
  test/resources/templates/echoserver-app.yaml.tpl
  test/system/shootdns_test.go
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/m

#180 Add Fluent Operator resources
  charts/gardener-extension-shoot-dns-service/templates/clusterfilters-logging.yaml
  charts/gardener-extension-shoot-dns-service/templates/clusterparsers-logging.yaml
  example/controller-registration.yaml
Labels: area/logging, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#183 Fix set_dependency_version_dnsman
  hack/.ci/set_dependency_version_dnsman
Labels: needs/ok-to-test, needs/review, size/xs

#185 Fix set_dependency_version
  .ci/set_dependency_version
Labels: needs/ok-to-test, needs/review, size/xs

#186 Fix set_dependency_version
  .ci/set_dependency_version
Labels: needs/ok-to-test, needs/review, size/xs

#187 Fix set_dependency_version
  .ci/set_dependency_version
Labels: needs/ok-to-test, needs/review, size/xs
