Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2023-08, with the labels that each got.

#226 Fix set_dependency_version for `workerlessSupported`
  .ci/set_dependency_version
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#224 Add dependabot to manage gardener packages
  .github/dependabot.yaml
  .github/workflows/vendor_gardener.yaml
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#223 Ensure dns-controller-manager is restarted on CA rotation
  charts/gardener-extension-shoot-dns-service/templates/dnsman-deployment.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#231 Fail if reading secret for external provider fails
  pkg/controller/lifecycle/actuator.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#232 Add support for projected volume kubeconfig
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-dns-service/values.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#233 Refactor imagevector package to conform to usage pattern in gardener/gardener
  .ci/set_dependency_version
  .dockerignore
  charts/charts.go
  imagevector/images.yaml
  imagevector/imagevector.go
  pkg/controller/lifecycle/actuator.go
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#235 Drop last usage of `github.com/golang/mock`
  go.mod
  go.sum
  hack/tools.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/golang/mock/mockgen/parse.go
  vendor/github.com/golang/mock/mockgen/reflect.go
  vendor/github.com/golang/mock/mockgen/version.1.11.go
  vendor/github.com/golang/mock/mockgen/version.1.12.go
  vendor/modules.txt
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#237 Add copy of images.yaml to charts dir to resolve RBSC issue
  .ci/set_dependency_version
  charts/images.yaml
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
