Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2024-10, with the labels that each got.

#374 Additional provider PowerDNS
  pkg/apis/service/validation/validation.go
  pkg/apis/service/validation/validation_test.go
Labels: area/networking, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#386 Fix integration test
  .test-defs/shootdns-test.yaml
  test/system/shootdns_test.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, needs/review, size/s

#387 Introduce `gosec` for Static Application Security Testing (SAST)
  .gitignore
  Makefile
  hack/api-reference/api.md
  hack/sast.sh
Labels: area/networking, area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s, area/compliance

#388 Bump `github.com/ahmetb/gen-crd-api-reference-docs` to master
  go.mod
  go.sum
  hack/api-reference/api.md
Labels: area/delivery, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#389 Add SAST logs to OCM component descriptor
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#392 Improve resource utilization of shoot-dns-service controller
  charts/internal/shoot-dns-service-seed/values.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/auto-scaling
