Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2024-01, with the labels that each got.

#277 Fix admission controller permissions
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/rbac.yaml
Labels: area/security, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#278 [release-v1.42] Fix admission controller permissions
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/security, kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs

#279 Revert "Upgrade dns-controller-manager (#274)"
  charts/gardener-extension-shoot-dns-service/values.yaml
  charts/images.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#280 Restrict admission controller permissions
  charts/gardener-extension-admission-shoot-dns-service/charts/application/templates/rbac.yaml
  cmd/gardener-extension-admission-shoot-dns-service/app/app.go
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#282 Update the golang version for the TestDefinition
  .test-defs/shootdns-test.yaml
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/testing

#281 Cleanup obsolete Go modules handling
  .ci/verify
  Makefile
  hack/api-reference/api.md
  hack/update-codegen.sh
Labels: area/open-source, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs
