Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2025-06, with the labels that each got.

#490 Upgrade github.com/gardener/external-dns-management (#489)
  charts/gardener-extension-shoot-dns-service/values.yaml
  charts/images.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: needs/review

#498 Remove `gardener/gardener-maintainers` from `CODEOWNERS` file
  CODEOWNERS
Labels: needs/ok-to-test

#500 Delete obsolete `dnsowners.dns.gardener.cloud` CRD
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrole.yaml
  cmd/gardener-extension-shoot-dns-service/app/app.go
  example/controller-registration.yaml
  go.mod
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/s

#502 Add `example/extension-shoot-dns-service.yaml` and update documentation
  Makefile
  docs/operations/configuration.md
  docs/operations/deployment.md
  example/extension-shoot-dns-service.yaml
  example/shoot-dns-service/base/doc.go
  example/shoot-dns-service/base/extension-patch.yaml
  example/shoot-dns-service/base/extension.yaml
  example/shoot-dns-service/base/kustomization.yaml
  example/shoot-dns-service/example/extension-patch.yaml
  example/shoot-dns-service/example/kustomization.yaml
  hack/prepare-operator-extension.sh
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/l
