Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2025-01, with the labels that each got.

#416 Save entry list compressed in extension state
  Makefile
  go.mod
  pkg/apis/helper/scheme.go
  pkg/controller/common/compressedstate.go
  pkg/controller/common/compressedstate_test.go
  pkg/controller/common/state.go
  test/integration/lifecycle/lifecycle_suite_test.go
  test/integration/lifecycle/state_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl, area/control-plane-migration

#420 Update golang dependencies
  go.mod
  go.sum
Labels: needs/ok-to-test

#421 feat: Add support for switching the `dns-controller-manager` image
  imagevector/images.yaml
Labels: kind/api-change, kind/task, needs/ok-to-test, reviewed/lgtm, size/xs, area/scalability

#423 fix: Add additional image to chart images
  charts/images.yaml
Labels: kind/task, needs/ok-to-test, reviewed/lgtm, size/xs, area/scalability

#426 Select dns-controller-manager image by seed-label
  charts/gardener-extension-shoot-dns-service/templates/_helpers.tpl
  charts/gardener-extension-shoot-dns-service/templates/dnsman-deployment.yaml
  charts/gardener-extension-shoot-dns-service/values-test.yaml
  charts/gardener-extension-shoot-dns-service/values.yaml
  charts/images.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#427 Forbid container privilege escalation
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-shoot-dns-service/templates/deployment.yaml
  charts/internal/shoot-dns-service-seed/templates/deployment.yaml
  example/10-fake-shoot-controlplane.yaml
  example/12-resource-manager-shoot.yaml
  example/13-resource-manager-seed.yaml
  example/controller-registration.yaml
  example/extension.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/compliance
