Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2025-04, with the labels that each got.

#458 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#460 Update base image to `debian12`
  Dockerfile
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#464 Cleanup permissions for deleting outdated CRDs
  charts/gardener-extension-shoot-dns-service/templates/dnsman-clusterrole.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#465 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-shoot-dns-service/templates/rbac.yaml
  example/controller-registration.yaml
Labels: area/control-plane, kind/task, needs/ok-to-test, reviewed/lgtm, size/xs

#454 Remove RBAC wildcard references
  charts/gardener-extension-shoot-dns-service/templates/rbac.yaml
  charts/internal/shoot-dns-service-seed/templates/rbac.yaml
  example/controller-registration.yaml
  example/extension.yaml
Labels: area/security, kind/enhancement, needs/ok-to-test, needs/rebase, needs/changes, needs/review, reviewed/lgtm, size/s, area/compliance
