Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2025-02, with the labels that each got.

#429 Prepare for deployment of admission controller by gardener-operator
  .ci/pipeline_definitions
  charts/gardener-extension-admission-shoot-dns-service/Chart.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/application/.helmignore
  charts/gardener-extension-admission-shoot-dns-service/charts/application/templates/_helpers.tpl
  charts/gardener-extension-admission-shoot-dns-service/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/application/templates/serviceaccount.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/application/values.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/.helmignore
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/secret-kubeconfig.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/service.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/vpa.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/values.yaml
  charts/gardener-extension-admission-shoot-dns-service/templates/_helpers.tpl
  charts/gardener-extension-admission-shoot-dns-service/values.yaml
  cmd/gardener-extension-admission-shoot-dns-service/app/app.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/l

#438 Delay reconciliation of `DNSEntries` during restore
  pkg/controller/replication/reconciler.go
Labels: area/control-plane, kind/bug, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#393 Drop support for Shoots with Kubernetes version <= 1.26
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/poddisruptionbudget.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/service.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-poddisruptionbudget.yaml
  charts/gardener-extension-shoot-dns-service/templates/poddisruptionbudget.yaml
  charts/internal/shoot-dns-service-seed/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
  hack/api-reference/service.json
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#444 Bump golang to 1.24 in pipeline
  .ci/pipeline_definitions
Labels: kind/task, needs/ok-to-test, reviewed/lgtm, size/xs, area/compliance
