Repository gardener/gardener-extension-shoot-dns-service, pull requests merged in 2025-08, with the labels that each got.

#524 Give build jobs pull-request write permission
  .github/workflows/build.yaml
Labels: area/delivery, kind/bug, needs/lgtm, reviewed/ok-to-test, size/xs

#527 docs: Document `AAAA` DNS records for dual-stack load balancers on AWS
  docs/usage/dns_names.md
  example/40-shoot-source-service.yaml
Labels: area/documentation, area/usability, kind/enhancement, kind/task, needs/ok-to-test, reviewed/lgtm, size/xs

#528 Validate provider secret data fields
  charts/gardener-extension-admission-shoot-dns-service/charts/application/templates/rbac.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/templates/deployment.yaml
  charts/gardener-extension-admission-shoot-dns-service/charts/runtime/values.yaml
  charts/gardener-extension-shoot-dns-service/templates/dnsman-crds.yaml
  example/20-crds.yaml
  example/controller-registration.yaml
  go.mod
  go.sum
  pkg/admission/validator/shoot_validator.go
  pkg/admission/validator/validator_suite_test.go
  pkg/admission/validator/validator_test.go
  pkg/apis/service/validation/validation.go
  pkg/apis/service/validation/validation_test.go
  pkg/controller/lifecycle/actuator.go
  pkg/controller/lifecycle/dnsprovider.go
Labels: area/ops-productivity, area/security, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xl

#521 Add 'gdch-dns' provider
  pkg/apis/service/validation/validation.go
  pkg/apis/service/validation/validation_test.go
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, needs/review, size/xs

#530 Upgrade github.com/gardener/external-dns-management from `v0.26.0` to…
  charts/gardener-extension-shoot-dns-service/values.yaml
  charts/images.yaml
  example/controller-registration.yaml
  imagevector/images.yaml
Labels: area/control-plane, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#531 Fix release permission issue: `pull-requests: write`
  .github/workflows/release.yaml
Labels: area/delivery, kind/task, needs/ok-to-test, reviewed/lgtm, size/xs

#536 Update the build badge from Concourse to GitHub Actions
  README.md
Labels: area/delivery, kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs

#537 Add `set -o pipefail` to react on `make generate` failure
  .github/workflows/build.yaml
Labels: kind/task, needs/ok-to-test, reviewed/lgtm, size/xs
